name: Test12 - Test Hetzner Cloud API

on:
  workflow_dispatch:

jobs:
  Get-Templates:
    runs-on: ubuntu-latest
  
    steps:
    - name: Install Hetzner Cloud Cli
      uses: hetznercloud/setup-hcloud@641015849308e9ed3e3b1f3d3b0a637068c5a2af # v1.0.1

    - name: Query Hetzner cloud project
      id: info
      #run: hcloud server-type list
      #run: hcloud image list --output "columns=ID,DESCRIPTION,ARCHITECTURE,DISK_SIZE" --type "snapshot" --sort "ID"
      #run: hcloud image list --output "columns=ID,DESCRIPTION,ARCHITECTURE,TYPE,LABELS,AGE" --type "snapshot" -l "os=ubuntu-24.04" -s "id"
      run: |
        echo "var=$(hcloud image list --output "columns=ID" --output "noheader" --type "snapshot" -l "os=ubuntu-24.04" -s "id:desc" | head -n 1)" >> $GITHUB_OUTPUT
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

    - name: Display Snapshot ID
      run: echo "${{ steps.info.outputs.var }}"
