name: Manage - Sync fork (Branch main)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
  workflow_call:

jobs:
  update_external_airflow_fork:
    name: Sync Fork
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:     
      - name: Generate app token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_SRP_ID }}
          private-key: ${{ secrets.GH_APP_SRP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Synchronize the given branch now
        uses: TobKed/github-forks-sync-action@2fb78daa46a630ff56455a63dec51ff00ba56e23 #v0.4.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          upstream_repository: actions/runner-images
          target_repository: dwydler/test1
          upstream_branch: main
          target_branch: main
          force: true
          tags: false
