name: Show env
on:
  workflow_dispatch:
  
env:
  somevar: 'lastvar'
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new created branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master

          
      - name: Is variable exported?
        run: git checkout -b develop
