name: Test tag exist
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - ubuntu22
        - ubuntu24
jobs:
#  BasicInformations:
#    runs-on: ubuntu-latest
#      
#    steps:
#      - name: Get current date
#        id: date
#        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
#    outputs:
      #ReleaseName: Ubuntu 24.04 (${{ steps.date.outputs.date }}) Image Update
      #ReleaseTag: ubuntu24/${{ steps.date.outputs.date }}.1
      #ReleaseDate: ${{ steps.date.outputs.date }}
#      ReleaseName: "Ubuntu 24.04 (20250311.1) Image Update"
#      ReleaseTag: "ubuntu24/20250311.1"
#      ReleaseDate: "20250311"

  Test:
#    needs: BasicInformations
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Find Tag
        id: tagger
        uses: digital-ai/query-tag-action@v2
        with:
          include: ubuntu24/20250312.*
          #exclude: '*-rc*'
          #commit-ish: 'HEAD'
          exact-match: 'false'
          # if you unshallow in a separate step, use the following option:
          # skip-unshallow: 'true'
      - name: Show Tag
        #if: steps.tagger.outputs.tag != 'NO_TAGS'
        if: ${{ (steps.tagger.outputs.tag != 'NO_TAGS') }}
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
    
#      - uses: mukunku/tag-exists-action@v1.6.0
#        id: check-tag
#        with: 
#          #tag: ${{ needs.BasicInformations.outputs.ReleaseTag }}
#          tag: ubuntu24/20250311.*
#          repo: 'dwydler/test1'

#      - name: Split branch name
#        env:
#          BRANCH: ${{ needs.BasicInformations.outputs.ReleaseTag }}
#        id: split
#        run: echo "fragment=${BRANCH##*/}" >> $GITHUB_OUTPUT
#
#      - name: Test variable
#        run: |
#          echo ${{ steps.split.outputs.fragment }}
#        
#      - name: determine docker tag by splitting branch name on slash
#        if: steps.check-tag.outputs.exists == 'true'
#        id: docker-tag
#        shell: bash
#        run: |
#          split=(${needs.BasicInformations.outputs.ReleaseTag//\// })
#          index=$((${#split[@]}-1))
#          DOCKER_TAG=${split[$index]}
#          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
#          echo "::set-output name=DOCKER_TAG::$DOCKER_TAG"
