name: Test tag exist
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Ubuntu Server OS
        options:
          - ubuntu24
          - ubuntu22
        required: true


jobs:

  BasicInformations:
    runs-on: ubuntu-latest
      
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        #run: echo "date=$(date +'%Y%m%d').1" >> $GITHUB_OUTPUT
        

      - name: Define the name of the OS
        id: osname
        #if: ${{ github.event.inputs.os }} == 'ubuntu22'
        #run: echo "Ubuntu 22.04" >> $GITHUB_OUTPUT
        #env: 
        #  os: ${{ github.event.inputs.os }}
        run: |
          if [ "${{ github.event.inputs.os }}" == "ubuntu22" ]; then
            echo "osname=Ubuntu 22.04" >> $GITHUB_OUTPUT
          else
            echo "osname=Ubuntu 24.04" >> $GITHUB_OUTPUT
          fi

      
      - name: Checkout the current repository
        uses: actions/checkout@v2
    
      - name: Find newest Git Tag
        id: tagger
        uses: digital-ai/query-tag-action@v2
        with:
          include: ${{ github.event.inputs.os }}/${{ steps.date.outputs.date }}.*
          exact-match: 'false'
          no-tags-text: 'false'


      - name: Create a new release name/tag
        #if: steps.tagger.outputs.tag != 'false'
        id: releasetagname
        #run: echo "::set-output name=date::$(date +'%Y%m%d').1"
        #run: echo "date=$(date +'%Y%m%d').1" >> $GITHUB_OUTPUT
        run: |
          if [ "${{ steps.tagger.outputs.tag }}" == "'false'" ]; then
            echo "var=$(date +'%Y%m%d').1" >> $GITHUB_OUTPUT
          else
            ver=$(echo "ubuntu24/20250312.2" | cut -d '.' -f 2)
            #ver=$ver+1
            ver=`expr $ver + 1`
            echo "var=$(date +'%Y%m%d').$ver" >> $GITHUB_OUTPUT
          fi
              
    outputs:
      ReleaseName: ${{ steps.osname.outputs.osname }} (${{ steps.releasetagname.outputs.var }}) Image Update
      ReleaseTag: ${{ github.event.inputs.os }}/${{ steps.releasetagname.outputs.var }}
      #ReleaseDate: ${{ steps.date.outputs.date }}


  CreateTest:
    needs: BasicInformations
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Write ReleaseName
        run: echo "${{ needs.BasicInformations.outputs.ReleaseName }}"

      - name: Write ReleaseTag
        run: echo "${{ needs.BasicInformations.outputs.ReleaseTag }}"
