name: Test16.01 - Matrix Test

on:
  workflow_dispatch:
    inputs:
      location:
         required: false
         type: choice
         options: 
           - hel1
           - fsn1
           - nbg1
         default: "hel1"
      servertype:
         required: false
         type: choice
         options: 
           - ccx13
         default: "ccx13"

  schedule:
    - cron: "0 4 * * 1"


jobs:
  Job:
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ['ubuntu20', 'ubuntu22', 'ubuntu24']

    uses: ./.github/workflows/test16.04_create-shr-image_ubuntuXX.yml
    with:
      os: ${{ matrix.os }}
      location: ${{ inputs.location }}
      servertype: ${{ inputs.servertype }}
    secrets: inherit
