name: Test create pr
on:
  workflow_dispatch:
    inputs:
      ReleaseName:
        description: 'Release Name'
        required: false
        #default: "Ubuntu 24.04 (20250302) Image Update"
        
      ReleaseTag:
        description: 'Release Tag'
        required: false
        #default: "ubuntu24/20250302.1"

jobs:
  BasicInformations:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8

        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
          
      - name: Build
        run: echo "building project"

      - name: Create PR
        uses: poorva17/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HEAD_BRANCH: development
          BASE_BRANCH: master
