name: Test11.01 - Create SHR Image (Ubuntu 24)

on:
  workflow_dispatch:
#    inputs:
#      os:
#        #type: choice
#        type: string
#        description: Ubuntu Server OS
#        #options:
#        #  - ubuntu24
#        #  - ubuntu22
#        required: true
#        default: "ubuntu24"

env:
  os: 'ubuntu24'
  
jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Get the current date2
        id: os
        run: echo "name=$os" >> $GITHUB_OUTPUT

      - name: Write ReleaseName
        run: echo "${{ steps.os.outputs.name }}"
        
    outputs:      
     OperatingSystem: ${{ steps.os.outputs.name }}

     
  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
     
    steps:
      - name: Write ReleaseName
        run: echo "${{ needs.Set-Variables.outputs.OperatingSystem }}"
#    uses: ./.github/workflows/test11_05_trigger_collect_informations.yml
#    with:
#      #os: ${{ github.event.inputs.os }}
#      #os: ${{ needs.Set-Variables.os.outputs.name }}
#      os: ${{ needs.Set-Variables.outputs.OperatingSystem }}

    
  Trigger-ImageBuilder:
    needs: Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
    secrets: inherit
