name: Create Release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'ubuntu24/'
          tag_template: 'yyyymmdd.i'

      - name: Test with environment variables
        run: echo ${{ steps.generate_release_tag.outputs.next_release_tag }}
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
                
#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
#          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
#          token: ${{secrets.GITHUB_TOKEN}}
#          generate_release_notes: true
