name: Test create pr
on:
  workflow_dispatch:
    inputs:
      ReleaseName:
        description: 'Release Name'
        required: false
        #default: "Ubuntu 24.04 (20250302) Image Update"
        
      ReleaseTag:
        description: 'Release Tag'
        required: false
        #default: "ubuntu24/20250302.1"

jobs:
  BasicInformations:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
          
      - run: exit 0
      
      - name: Create PR
        uses: poorva17/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HEAD_BRANCH: ubuntu24/20250310.1
#      - name: Checkout new created branch
#        uses: actions/checkout@v4
#        with:
#          ref: ubuntu24/20250310.1

#      - name: Create PR
#        uses: poorva17/create-pr-action@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          HEAD_BRANCH: ubuntu24/20250310.1
#          BASE_BRANCH: master
