name: Test16.03 - Create SHR Image (Ubuntu 22)

on:      
   workflow_dispatch:
     inputs:
       location:
        type: choice 
        required: true
        options: 
          - hel1
          - fsn1
          - nbg1
        default: "hel1"
       servertype:
        type: choice 
        required: true
        options:
          - cx32
          - cpx21
          - ccx13  
        default: "cx32"


env:
  os: "ubuntu22"

jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Assign ENV variable to workflow variable
        id: env
        run: |
           echo "os=$os" >> $GITHUB_OUTPUT

      - name: Display Variable server os
        run: echo "${{ steps.env.outputs.os }}"

      - name: Display Variable server location
        run: echo "${{ inputs.location }}"

      - name: Display Variable server type
        run: echo "${{ inputs.servertype }}"
     
    outputs:      
      os: ${{ steps.env.outputs.os }}


  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/test16.05_trigger_collect_informations.yml
    with:
      #os: ${{ inputs.os }}
      os: ${{ needs.Set-Variables.outputs.os }}

    
  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/test16.07-trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
      readme_file: ${{ needs.Trigger-CollectInformations.outputs.ReadmeFile }}

      hcloud_server_location: ${{ inputs.location }}
      hcloud_server_type: ${{ inputs.servertype }}
      
      hcloud_name: ${{ needs.Trigger-CollectInformations.outputs.HCloudObjectName }}
      hcloud_server_image: ${{ needs.Trigger-CollectInformations.outputs.HCloudServerImage }}
      
    secrets: inherit


  Trigger-CleanupOnFailure:
    if: ${{ failure() || cancelled() }}

    needs:
      - Set-Variables
      - Trigger-CollectInformations
      - Trigger-ImageBuilder

    permissions:
      contents: write

    uses: ./.github/workflows/test16.09_trigger-cleanup-onfailure.yml
    with:
      ReleaseTag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      HCloudObjectName: ${{ needs.Trigger-CollectInformations.outputs.HCloudObjectName  }}

    secrets: inherit 
