name: "Delete old hetzner snapshots"

on:
  workflow_dispatch:


jobs: 
  Preparations:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hetzner Cloud Cli
        uses: hetznercloud/setup-hcloud@641015849308e9ed3e3b1f3d3b0a637068c5a2af # v1.0.1

  Delete:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['ubuntu20', 'ubuntu22', 'ubuntu24']

    steps:
      - id: one
        run: |
          echo "id=$(hcloud image list --output "columns=ID" --output "noheader" --type "snapshot" -l "os=${{ matrix.image }}" -s "id:desc" | head -n 1)" >> $GITHUB_OUTPUT
  
