name: Test16.01 - Matrix Test

on:
  workflow_dispatch:
    inputs:
      location:
         required: false
         type: choice
         options: 
           - hel1
           - fsn1
           - nbg1
         default: "hel1"
      servertype:
         required: false
         type: choice
         options: 
           - ccx13
         default: "ccx13"

  schedule:
    - cron: "50 18 * * 1"

env:
  location: ${{ github.event_name == 'schedule' && 'hel1' || github.event.inputs.location }}
  servertype: ${{ github.event_name == 'schedule' && 'ccx13' || github.event.inputs.servertype }}
  
jobs:
  Job:
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ['ubuntu20', 'ubuntu22', 'ubuntu24']

    uses: ./.github/workflows/test16.04_create-shr-image_ubuntuXX.yml
    with:
      os: ${{ matrix.os }}
      location: ${{ env.location }}
      servertype: ${{ env.servertype }}
    secrets: inherit
