name: Test11.01 - Create SHR Image (Ubuntu 24)

on:
  workflow_dispatch:
#    inputs:
#      os:
#        #type: choice
#        type: string
#        description: Ubuntu Server OS
#        #options:
#        #  - ubuntu24
#        #  - ubuntu22
#        required: true
#        default: "ubuntu24"

env:
  os: "ubuntu24"
  
jobs:
  Trigger-CollectInformations:

    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/test11_05_trigger_collect_informations.yml
    with:
      #os: ${{ github.event.inputs.os }}
      os: $os
    
  Trigger-ImageBuilder:
    needs: Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
    secrets: inherit
