name: Test11.01 - Create SHR Image (Ubuntu 24)

on:
  workflow_dispatch:

env:
  os: 'ubuntu24'
  
jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Assign environment variables to a job variable
        id: os
        run: echo "name=$os" >> $GITHUB_OUTPUT

      - name: Write ReleaseName
        run: echo "${{ steps.os.outputs.name }}"

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
    outputs:      
     OperatingSystem: ${{ steps.os.outputs.name }}
     GitHubAppToken: ${{ steps.generate-token.outputs.token }}
     
  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/test11_05_trigger_collect_informations.yml
    with:
      os: ${{ needs.Set-Variables.outputs.OperatingSystem }}

    
  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
    secrets:
      access_token: ${{ needs.Set-Variables.outputs.GitHubAppToken }}
