name: Test11.01 - Create SHR Image (Ubuntu 24)

on:
  workflow_dispatch:

env:
  os: 'ubuntu24'

  hcloud_server_location: "hel1"
  hcloud_server_image: "ubuntu-24.04"
  hcloud_server_type: "ccx13"
  
jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Assign ENV variable to workflow variable
        id: env
        run: |
          echo "os=$os" >> $GITHUB_OUTPUT

          echo "serverlocation=$hcloud_server_location" >> $GITHUB_OUTPUT
          echo "serverimage=$hcloud_server_image" >> $GITHUB_OUTPUT
          echo "servertype=$hcloud_server_type" >> $GITHUB_OUTPUT

      - name: Display Variable os
        run: echo "${{ steps.env.outputs.os }}"

      - name: Display Variable serverlocation
        run: echo "${{ steps.env.outputs.serverlocation }}"

      - name: Display Variable serverimage
        run: echo "${{ steps.env.outputs.serverimage }}"

      - name: Display Variable servertype
        run: echo "${{ steps.env.outputs.servertype }}"
        
    outputs:      
     OperatingSystem: ${{ steps.env.outputs.os }}
     HCloudServerLocation: ${{ steps.env.outputs.serverlocation }}
     HCloudServerImage: ${{ steps.env.outputs.serverimage }}
     HCloudServerType: ${{ steps.env.outputs.servertype }}
     
     
  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/test11_05_trigger_collect_informations.yml
    with:
      os: ${{ needs.Set-Variables.outputs.OperatingSystem }}

    
  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}

      hcloud_server_location: ${{ needs.Set-Variables.outputs.HCloudServerLocation }}
      hcloud_server_image: ${{ needs.Set-Variables.outputs.HCloudServerImage }}
      hcloud_server_type: ${{ needs.Set-Variables.outputs.HCloudServerType }}
      
    secrets: inherit


  CleanupOnFailure:
    if: ${{ failure() || cancelled() }}

    needs:
      - Set-Variables
      - Trigger-CollectInformations
      - Trigger-ImageBuilder
      
    runs-on: ubuntu-latest

    steps:
      - name: Display text
        run: echo "Hallo"

      - name: Generate app token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Delete PRs head branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          branches: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
