name: Test15.01 - GitHub concurrency Job02

on:
  workflow_dispatch:

concurrency:
  group: group-name
  cancel-in-progress: true

  
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Waiting for 1 minute(s)
        run: sleep 5m &&  ls
