name: Test create pr2
on:
  workflow_dispatch:
  
jobs:
  BasicInformations:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout this repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
#        with:
#          ref: ubuntu24/20250310.1

      
      - name: Create Pull Request for the change
        id: cpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: test2
          signoff: false
          branch: test1
          delete-branch: false
          title: test3
          body: |
              Bump mediathekview/MediathekView from ${{ needs.tag-new-versions.outputs.mv_local_version }} to ${{ needs.tag-new-versions.outputs.mv_original_version }}.
          #    - Updated with *today's* date
          labels: |
            dependencies
          draft: false
          assignees: dwydler
