name: Create Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #tag_prefix: 'ubuntu24/'
          tag_template: 'yyyymmdd.i'

      - name: Generate release name
        id: generate_release_name
        uses: amitsingh-007/next-release-tag@v6.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #tag_prefix: 'Ubuntu 24.04'
          tag_template: 'yyyymmdd.i'


      - name: Test with environment variables
        run: echo ${{ steps.generate_release_tag.outputs.next_release_tag }}
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}

                
      - name: Create a new release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ubuntu24/${{ steps.generate_release_tag.outputs.next_release_tag }}
          name: Ubuntu 24.04 (${{ steps.generate_release_name.outputs.next_release_tag }}) Image Update
          body: ${{ steps.ghpages.outputs.content }}
          token: ${{ secrets.GH_TOKEN }}
