name: Test create pr
on:
  workflow_dispatch:
    inputs:
      ReleaseName:
        description: 'Release Name'
        required: false
        #default: "Ubuntu 24.04 (20250302) Image Update"
        
      ReleaseTag:
        description: 'Release Tag'
        required: false
        #default: "ubuntu24/20250302.1"

jobs:
  BasicInformations:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout new created branch
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Write new version number to file
        run: echo "hallo"  > test1
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: test1
          signoff: false
          delete-branch: false
          title: test4
          branch: ubuntu24/20250310.1
          base: master
          draft: false
