name: Test16.0.03 - Create SHR Image (Ubuntu 22)

on:
   workflow_call:
    inputs:
      os:
        required: true
        type: string
      location:
        required: true
        type: string
      servertype:
        required: false
        type: string
        default: "ccx13"
        
   workflow_dispatch:
     inputs:
       os:
         type: string
         required: true
         default: "ubuntu22"
       location:
         type: choice
         options: 
           - hel1
           - fsn1
           - nbg1
       servertype:
         required: true
         type: string
         default: "ccx13"
         
  
jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Display Variable server os
        run: echo "${{ inputs.os }}"

      - name: Display Variable server location
        run: echo "${{ inputs.location }}"

      - name: Display Variable server type
        run: echo "${{ inputs.servertype }}"
     
     
  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/test16.05_trigger_collect_informations.yml
    with:
      os: ${{ inputs.os }}

    
  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/test16.07-trigger-build-workflow-ubuntu.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Trigger-CollectInformations.outputs.HclFile }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
      readme_file: ${{ needs.Trigger-CollectInformations.outputs.ReadmeFile }}

      hcloud_server_location: ${{ inputs.location }}
      hcloud_server_type: ${{ inputs.servertype }}
      
      hcloud_name: ${{ needs.Trigger-CollectInformations.outputs.HCloudObjectName }}
      hcloud_server_image: ${{ needs.Trigger-CollectInformations.outputs.HCloudServerImage }}
      
    secrets: inherit


  Trigger-CleanupOnFailure:
    if: ${{ failure() || cancelled() }}

    needs:
      - Set-Variables
      - Trigger-CollectInformations
      - Trigger-ImageBuilder

    permissions:
      contents: write

    uses: ./.github/workflows/test16.09_trigger-cleanup-onfailure.yml
    with:
      ReleaseTag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      HCloudObjectName: ${{ needs.Trigger-CollectInformations.outputs.HCloudObjectName  }}

    secrets: inherit 
