name: "Delete old hetzner snapshots"

on:
  workflow_dispatch:


jobs:
  Delete:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']

    steps:
      - name: Install Hetzner Cloud Cli
        uses: hetznercloud/setup-hcloud@641015849308e9ed3e3b1f3d3b0a637068c5a2af # v1.0.1
        
      - name: Query Hetzner cloud project
        id: hlcoud_snapshot
        run: |
          echo "id=$(hcloud image list --output "columns=ID" --output "noheader" --type "snapshot" -l "os=${{ matrix.image }}" -s "id:desc" | tail -n +2)"
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
