name: "Delete old hetzner snapshots"

on:
  workflow_dispatch:


jobs: 
  Preparations:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hetzner Cloud Cli
        uses: hetznercloud/setup-hcloud@641015849308e9ed3e3b1f3d3b0a637068c5a2af # v1.0.1

  Job:
    needs: Preparations
    
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        image: ['ubuntu20-04', 'ubuntu22-04', 'ubuntu24-04']

      steps:
        - id: one
          run: |
            echo "id=$(hcloud image list --output "columns=ID" --output "noheader" --type "snapshot" -l "os=${{ matrix.image }}" -s "id:desc" | head -n 1)" >> $GITHUB_OUTPUT
          env:
            HCLOUD_TOKEN: ${{ secrets.HETZNER_CLOUD_GITHUB_SELF_HOSTED_RUNNERS }}
