name: Test15.01 - GitHub concurrency Job01

on:
  workflow_dispatch:

concurrency:
  group: group-name
  cancel-in-progress: false

  
jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    steps:
      - name: Assign ENV variable to workflow variable
        run: sleep 1m &&  ls
