name: "Delete old hetzner snapshots"

on:
  workflow_dispatch:


jobs: 
  Preparations:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hetzner Cloud Cli
        uses: hetznercloud/setup-hcloud@641015849308e9ed3e3b1f3d3b0a637068c5a2af # v1.0.1

  Delete:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu20', 'ubuntu22', 'ubuntu24']

    steps:
      - id: one
        run: |
          mkdir -p pipelines
          echo ${{ matrix.kv.val }} >> outputs/${{ matrix.kv.key }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/*.txt
