name: Test10-Startpunkt

on:
  workflow_dispatch:

jobs:
  job01:
    uses: ./.github/workflows/test10.yml

  job02:
    runs-on: ubuntu-latest
     
    steps:
      - name: Write ReleaseName
        run: echo "${{ jobs.jobs01.outputs.result.value }}"
