name: Mediathekview Updates
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
#        options: 
#        - monalisa
#        - cschleiden
#      message:
#        required: true

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: actions/runner-images  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
          prefix: 'ubuntu24'
        id: octokit  # The step ID to refer to later.
    
      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: ${{ steps.octokit.outputs.tag }}
          #sha: '${{ github.event.pull_request.head.sha }}'

      - name: Checkout new created branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.octokit.outputs.tag }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init /images/ubuntu/templates/ubuntu-24.04.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate /images/ubuntu/templates/ubuntu-24.04.pkr.hcl"

      - name: Run `packer validate`
        id: build
        run: "packer build /images/ubuntu/templates/ubuntu-24.04.pkr.hcl"

        
      - name: Read README.md(gh-pages)
        id: ghpages
        uses: jaywcjlove/github-action-read-file@v2.0.0
        with:
          branch: ${{ steps.octokit.outputs.tag }}
          path: ./images/ubuntu/Ubuntu2404-Readme.md
      
      - name: Echo README.md(gh-pages)
        run: echo "${{ steps.ghpages.outputs.content }}"


      - name: Create release for ${{ steps.octokit.outputs.tag }}
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.octokit.outputs.tag }}
          name: ${{ github.event.client_payload.ReleaseTitle }}
          body: ${{ steps.ghpages.outputs.content }}
          prerelease: ${{ github.event.client_payload.Prerelease }}
          commit: ${{ github.event.client_payload.Commitish }}
          token: ${{ secrets.GH_TOKEN }}
