name: Mediathekview Updates
on:
  workflow_dispatch:

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: actions/runner-images  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
          prefix: 'ubuntu24'
        id: octokit  # The step ID to refer to later.
    
      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"

      - uses: peterjgrainger/action-create-branch@v2.2.0
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.octokit.outputs.tag }}
          #sha: '${{ github.event.pull_request.head.sha }}'
