name: Validate JSON Schema

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
